model: BiGCN                          # Name of your model (optional)
type: human                               # human, llm, or human+llm
notes: Data augmentation to manage small dataset  # Brief description (optional)